<?php
/**
 * SuperPWA integration for Bodø Modellflyklubb.
 *
 * @package BMFK
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Open the installed app at the live webcam section.
 *
 * A query parameter is used as the manifest start URL because a fragment-only
 * URL is not preserved consistently when a PWA is installed. The front-end
 * script converts this marker to /#webkamera after the page has loaded.
 *
 * @param string $start_url Start URL generated by SuperPWA.
 * @return string
 */
function bmfk_superpwa_start_url( $start_url ) {
	return home_url( '/?bmfk_pwa=webkamera' );
}
add_filter( 'superpwa_manifest_start_url', 'bmfk_superpwa_start_url', 10000 );

/**
 * Regenerate SuperPWA's manifest once after the camera start URL is installed.
 *
 * Replacing an already active theme does not run after_switch_theme, so this
 * task runs the first time an administrator opens WordPress after the update.
 */
function bmfk_activate_superpwa_camera_start() {
	if ( ! function_exists( 'superpwa_generate_manifest' ) ) {
		return;
	}

	if ( '1.6.13' === get_option( 'bmfk_superpwa_camera_start_version' ) ) {
		return;
	}

	superpwa_generate_manifest();
	update_option( 'bmfk_superpwa_camera_start_version', '1.6.13', false );
}
add_action( 'admin_init', 'bmfk_activate_superpwa_camera_start', 30 );
